import { jsPDF } from "jspdf";

const PDF_FILENAME = "spindraw-winners.pdf";

export function downloadWinnersPdf(winners: string[], totalParticipants: number): void {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(30, 27, 75);
  doc.text("SpinDraw — Raffle Results", 20, 24);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  doc.text(`Date: ${date}`, 20, 34);
  doc.text(`Total participants: ${totalParticipants}`, 20, 41);
  doc.text(`Winners drawn: ${winners.length}`, 20, 48);

  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.5);
  doc.line(20, 54, 190, 54);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(30, 27, 75);
  doc.text("Winners", 20, 64);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);

  let y = 74;
  winners.forEach((name, i) => {
    if (y > 275) {
      doc.addPage();
      y = 24;
    }
    doc.setFont("helvetica", "bold");
    doc.text(`${i + 1}.`, 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(name, 32, y);
    y += 9;
  });

  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by SpinDraw · spindraw.de", 20, 285);

  doc.save(PDF_FILENAME);
}
